### ISSUE TITLE
RuntineError: Expected all tensors to be on the same device, but found at least two devices,cuda:0 and cpu!

### ISSUE THREAD

**Issue by giaovarus** [inisis/caffe#3]
Traceback (most recent call last):
  File "/media/3255035b-77ce-41e8-8665-808657363219/deep-learning/predict_floder.py", line 146, in <module>
    main()
  File "/media/3255035b-77ce-41e8-8665-808657363219/deep-learning/predict_floder.py", line 102, in main
    pytorch_parser = PytorchCaffeParser(model,x.to(device))
  File "/home/miniconda3/envs/py39/lib/python3.9/site-packages/brocolli/converter/pytorch_caffe_parser.py", line 45, in __init__
    self.pytorch_graph = PytorchGraph(self.model, self.inputs, self.concrete_args)
  File "/home/miniconda3/envs/py39/lib/python3.9/site-packages/brocolli/converter/pytorch_graph.py", line 102, in __init__
    self.shape_inference()
  File "/home/miniconda3/envs/py39/lib/python3.9/site-packages/brocolli/converter/pytorch_graph.py", line 171, in shape_inference
    shape_runner.run(*self.inputs)
  File "/home/miniconda3/envs/py39/lib/python3.9/site-packages/torch/fx/interpreter.py", line 136, in run
    self.env[node] = self.run_node(node)
  File "/home/miniconda3/envs/py39/lib/python3.9/site-packages/brocolli/converter/pytorch_graph.py", line 49, in run_node
    result = super().run_node(n)
  File "/home/miniconda3/envs/py39/lib/python3.9/site-packages/torch/fx/interpreter.py", line 177, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/miniconda3/envs/py39/lib/python3.9/site-packages/torch/fx/interpreter.py", line 249, in call_function
    return target(*args, **kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

While executing %mul_22 : [#users=1] = call_function[target=operator.mul](args = (%truediv_4, %norm_weight), kwargs = {})
Original traceback:
None

**Comment by inisis** [comment]
Hi，you can raise an issue in brocolli, but not in caffe.
